# For more information see:
# https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NLM Release

on:
  push:
    branches: [ master ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx nlm release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}